# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2de21531d6808977a2dd817faa97902375312e147c2e077e03788260d124cf64c3b51e1c1263e19f88ba746e80d12ca0bec0213b24bbcedddcf56370c0c6db9f

test:
  secret_key_base: f17f2d75e6187f5675cd441553ae4c9e15ea136d04308df9eac39ca6d0cfa6a922ba029f2e3aba0981a7c214f689f4ff377fdeb679e67b4a4e6276f665ad8bdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
